// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationCard: typeof import('./src/components/applicationCard.vue')['default']
    GridComponent: typeof import('./src/components/gridComponent.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpandTransition: typeof import('vuetify/lib')['VExpandTransition']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
