/*
 * Copyright 2022 SpinalCom - www.spinalcom.com
 *
 * This file is part of SpinalCore.
 *
 * Please read all of the following terms and conditions
 * of the Free Software license Agreement ("Agreement")
 * carefully.
 *
 * This Agreement is a legally binding contract between
 * the Licensee (as defined below) and SpinalCom that
 * sets forth the terms and conditions that govern your
 * use of the Program. By installing and/or using the
 * Program, you agree to abide by all the terms and
 * conditions stated or referenced herein.
 *
 * If you do not agree to abide by these terms and
 * conditions, do not demonstrate your acceptance and do
 * not install or use the Program.
 * You should have received a copy of the license along
 * with this file. If not, see
 * <http://resources.spinalcom.com/licenses.pdf>.
 */

// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ApplicationCard: (typeof import("./src/components/applicationCard.vue"))["default"];
    GridComponent: (typeof import("./src/components/gridComponent.vue"))["default"];
    Nav: (typeof import("./src/components/nav.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Select: (typeof import("./src/components/select.vue"))["default"];
    VAlert: (typeof import("vuetify/lib"))["VAlert"];
    VApp: (typeof import("vuetify/lib"))["VApp"];
    VBtn: (typeof import("vuetify/lib"))["VBtn"];
    VCard: (typeof import("vuetify/lib"))["VCard"];
    VCardActions: (typeof import("vuetify/lib"))["VCardActions"];
    VCardText: (typeof import("vuetify/lib"))["VCardText"];
    VCardTitle: (typeof import("vuetify/lib"))["VCardTitle"];
    VChip: (typeof import("vuetify/lib"))["VChip"];
    VCol: (typeof import("vuetify/lib"))["VCol"];
    VContainer: (typeof import("vuetify/lib"))["VContainer"];
    VDataTable: (typeof import("vuetify/lib"))["VDataTable"];
    VDivider: (typeof import("vuetify/lib"))["VDivider"];
    VDialog: (typeof import("vuetify/lib"))["VDialog"];
    VExpandTransition: (typeof import("vuetify/lib"))["VExpandTransition"];
    VFlex: (typeof import("vuetify/lib"))["VFlex"];
    VForm: (typeof import("vuetify/lib"))["VForm"];
    VIcon: (typeof import("vuetify/lib"))["VIcon"];
    VImg: (typeof import("vuetify/lib"))["VImg"];
    VLayout: (typeof import("vuetify/lib"))["VLayout"];
    VList: (typeof import("vuetify/lib"))["VList"];
    VListGroup: (typeof import("vuetify/lib"))["VListGroup"];
    VListItem: (typeof import("vuetify/lib"))["VListItem"];
    VListItemIcon: (typeof import("vuetify/lib"))["VListItemIcon"];
    VListItemTitle: (typeof import("vuetify/lib"))["VListItemTitle"];
    VMain: (typeof import("vuetify/lib"))["VMain"];
    VMenu: (typeof import("vuetify/lib"))["VMenu"];
    VRow: (typeof import("vuetify/lib"))["VRow"];
    VSelect: (typeof import("vuetify/lib"))["VSelect"];
    VTextarea: (typeof import("vuetify/lib"))["VTextarea"];
    VTextField: (typeof import("vuetify/lib"))["VTextField"];
    VTooltip: (typeof import("vuetify/lib"))["VTooltip"];
  }
}
