FROM node:22-alpine as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS ssh-init
RUN apk add --update --no-cache openssh-client git \
    && mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN apk add --no-cache python3 make g++

FROM ssh-init AS dev-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    --mount=type=ssh \
    pnpm install

FROM base
COPY --from=dev-deps /app/node_modules /app/node_modules
EXPOSE 1235
CMD [ "pnpm", "serve:webpack" ]